/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hook/useNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/../reminder-app/app${'/(tabs)'}/index` | `/../reminder-app/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/newReminder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/hamburger/pastReminders`; params?: Router.UnknownInputParams; } | { pathname: `/hamburger/trashbin`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../hook/useNotifications`; params?: Router.UnknownOutputParams; } | { pathname: `/../reminder-app/app${'/(tabs)'}/index` | `/../reminder-app/app/index`; params?: Router.UnknownOutputParams; } | { pathname: `/newReminder`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/hamburger/pastReminders`; params?: Router.UnknownOutputParams; } | { pathname: `/hamburger/trashbin`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../hook/useNotifications${`?${string}` | `#${string}` | ''}` | `/../reminder-app/app${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/../reminder-app/app/index${`?${string}` | `#${string}` | ''}` | `/newReminder${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/hamburger/pastReminders${`?${string}` | `#${string}` | ''}` | `/hamburger/trashbin${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../hook/useNotifications`; params?: Router.UnknownInputParams; } | { pathname: `/../reminder-app/app${'/(tabs)'}/index` | `/../reminder-app/app/index`; params?: Router.UnknownInputParams; } | { pathname: `/newReminder`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/hamburger/pastReminders`; params?: Router.UnknownInputParams; } | { pathname: `/hamburger/trashbin`; params?: Router.UnknownInputParams; };
    }
  }
}
